import { CompileResult, SimulationResult, InterruptType } from './8085/types';
import { Assembler8085 } from './8085/assembler';
import { WasmCompiler8085 } from './8085/wasm-compiler';
import { CPU8085 } from './8085/cpu';

export class WorkerClient {
  private static swRegistered = false;
  private static worker: Worker | null = null;

  // Persistent CPU instance for interrupt continuation
  private static activeCpu: CPU8085 | null = null;
  private static activeAddressLineMap: Map<number, number> | null = null;

  public static registerServiceWorker(): void {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator && !this.swRegistered) {
      navigator.serviceWorker
        .register('/sw.js')
        .then((reg) => {
          console.log('[8085 SW] Service worker registered with scope:', reg.scope);
          this.swRegistered = true;
        })
        .catch((err) => {
          console.warn('[8085 SW] Service worker registration error:', err);
        });
    }
  }

  /**
   * Step 1: Compile 8085 source code
   * Checks syntax errors, generates symbol table, machine code, and WebAssembly (.wasm) binary.
   */
  public static compile(source: string): CompileResult {
    const assembler = new Assembler8085();
    const result = assembler.assemble(source);

    if (result.success && result.machineCode.length > 0) {
      try {
        const wasm = WasmCompiler8085.compile(result.machineCode, result.startAddress);
        result.wasmBinary = wasm;
      } catch (e) {
        console.error('WASM compilation failed:', e);
      }
    }

    return result;
  }

  /**
   * Step 2: Run simulation and generate micro-step trace.
   * Preserves the CPU instance for interrupt continuation if the program
   * enters an infinite loop waiting for hardware interrupts.
   */
  public static simulate(
    compileResult: CompileResult,
    initialMemory?: { address: number; values: number[] }[],
    maxSteps = 3000
  ): SimulationResult {
    const cpu = new CPU8085();

    // 1. Load initial memory if any (e.g. array data)
    if (initialMemory) {
      for (const block of initialMemory) {
        for (let i = 0; i < block.values.length; i++) {
          cpu.memory[(block.address + i) & 0xFFFF] = block.values[i];
        }
      }
    }

    // 2. Load compiled program
    cpu.loadProgram(compileResult.startAddress, compileResult.machineCode, compileResult.entryAddress);

    // 3. Simulate and collect all execution steps
    const steps = cpu.simulate(compileResult.addressLineMap, maxSteps);
    const waitingForInterrupt = cpu.isWaitingForInterrupt();

    // 4. Preserve CPU state if waiting for interrupt
    if (waitingForInterrupt) {
      this.activeCpu = cpu;
      this.activeAddressLineMap = compileResult.addressLineMap;
    } else {
      this.activeCpu = null;
      this.activeAddressLineMap = null;
    }

    return {
      success: true,
      steps,
      totalCycles: cpu.getCycles(),
      finalRegisters: cpu.getRegisterState(),
      finalFlags: cpu.getFlags(),
      memory: new Uint8Array(cpu.memory),
      waitingForInterrupt,
    };
  }

  /**
   * Trigger a hardware interrupt and continue simulation from the waiting state.
   * Returns the new steps generated by the ISR execution, or null if no CPU is waiting.
   */
  public static triggerInterrupt(
    interruptType: InterruptType,
    currentStepCount: number,
  ): SimulationResult | null {
    if (!this.activeCpu || !this.activeAddressLineMap) return null;

    const newSteps = this.activeCpu.simulateAfterInterrupt(
      interruptType,
      currentStepCount,
      this.activeAddressLineMap,
    );

    const lastStep = newSteps[newSteps.length - 1];
    const stillWaiting = this.activeCpu.isWaitingForInterrupt();
    const resultCpu = this.activeCpu;

    if (!stillWaiting) {
      // Simulation fully completed after the ISR
      this.activeCpu = null;
      this.activeAddressLineMap = null;
    }

    return {
      success: true,
      steps: newSteps,
      totalCycles: resultCpu?.getCycles() ?? 0,
      finalRegisters: resultCpu?.getRegisterState() ?? lastStep?.registers ?? { A: 0, B: 0, C: 0, D: 0, E: 0, H: 0, L: 0, W: 0, Z: 0, TEMP: 0, PC: 0, SP: 0 },
      finalFlags: resultCpu?.getFlags() ?? { s: false, z: false, ac: false, p: false, cy: false },
      memory: resultCpu ? new Uint8Array(resultCpu.memory) : new Uint8Array(65536),
      waitingForInterrupt: stillWaiting,
    };
  }

  /** Check if a CPU is currently waiting for an interrupt */
  public static isWaitingForInterrupt(): boolean {
    return this.activeCpu !== null;
  }
}
